### ISSUE TITLE
Surname before Firstname

### ISSUE THREAD

**Issue by pgancarski** [Marinet2/metadata-schema#3]
In Zenodo and other places I tend to see "Surnames, Forenames" for creators/contributors.
I think it is recommended by DC, but I am not sure about it.

Currently the yaml files suggest:
contributor_name: ['FirstName_1 LastName_1', 'FirstName_2 LastName_2']
I would change that to:
contributor_name: [' LastName_1, FirstName_1', ' LastName_2, FirstName_2']

**Comment by nikokaoja** [comment]
Fixed according to the suggestion!
