### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by pgancarski** [Marinet2/metadata-schema#5]
https://github.com/Marinet2/metadata-schema/blob/35d22670a810e0bead7b6bb6ed547311e2c6f9a7/dataset_schema.yaml#L266

Replace:
http://cfconventions.org/cf-conventions/v1.8.0/cf-conventions.html#_features_and_feature_types
With:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_features_and_feature_types

**Comment by nikokaoja** [comment]
Fixed
